# Generated by Django 5.2.7 on 2025-10-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('packet_size', models.IntegerField()),
                ('flow_duration', models.FloatField()),
                ('src_bytes', models.IntegerField()),
                ('dst_bytes', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('flag', models.CharField(max_length=10)),
                ('prediction', models.CharField(max_length=20)),
            ],
        ),
    ]
